### PR TITLE
Updated newrelic_rpm

### PR DESCRIPTION
**Pull request by crossman**
Switching to an updated version of newrelic_rpm because of security flaw in prior versions.

[Ruby Agent Security Notification](https://newrelic.com/docs/ruby/ruby-agent-security-notification)

### CODE REVIEW

**Comment by crossman** [comment]
I didn't see any actual code changes required, and this is running stable for us.

**Comment by benjaminoakes** [comment]
Thanks for making this PR.  I was doing the same change on my end.  However, when I use this on Heroku (Bamboo, Ruby 1.8.7), I get errors like this:

```
undefined method `config' for NewRelic::Agent:Module
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/lib/new_relic/delayed_job_injection.rb:18
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:56:in `call'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:56:in `check_dependencies'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/lib/new_relic/delayed_job_injection.rb:10:in `all?'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:56:in `each'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:56:in `all?'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:56:in `check_dependencies'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:44:in `dependencies_satisfied?'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:14:in `detect!'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:13:in `each'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/vendor/gems/dependency_detection-0.0.1.build/lib/dependency_detection.rb:13:in `detect!'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/lib/new_relic/delayed_job_injection.rb:50
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:223:in `load_dependency'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:640:in `new_constants_in'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:223:in `load_dependency'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/lib/new_relic/agent/samplers/delayed_job_sampler.rb:2
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:223:in `load_dependency'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:640:in `new_constants_in'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:223:in `load_dependency'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/lib/new_relic/agent.rb:101
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:223:in `load_dependency'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:640:in `new_constants_in'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:223:in `load_dependency'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/.bundle/gems/ruby/1.8/gems/newrelic_rpm-3.5.3.25/lib/new_relic/control.rb:20
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:223:in `load_dependency'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:640:in `new_constants_in'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:223:in `load_dependency'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `require'
/app/vendor/gems/padrino-rpm/lib/padrino-rpm.rb:39
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `call'
/app/.bundle/gems/ruby/1.8/gems/activesupport-3.1.8/lib/active_support/dependencies.rb:240:in `to_proc'
/app/.bundle/gems/ruby/1.8/gems/padrino-core-0.10.5/lib/padrino-core/loader.rb:69:in `each'
/app/.bundle/gems/ruby/1.8/gems/padrino-core-0.10.5/lib/padrino-core/loader.rb:69:in `load!'
/app/config/boot.rb:39
/app/Rakefile:2:in `require'
/app/Rakefile:2
```

It doesn't sound like you have the same issue.  Are you also using Heroku, or something else?

**Comment by crossman** [comment]
I'm using a custom environment in EC2 with ruby 1.9.3.

**Comment by crossman** [comment]
@benjaminoakes were you able to diagnose that at all?

**Comment by Pro777** [comment]
New Relic is throwing warnings in their console to update the newrelic_rpm version. I tested this update and am not having trouble @benjaminoakes though I'm not running in Heroku. Everything is reporting to New Relic correctly.

**Comment by crossman** [comment]
@benjaminoakes I started putting this into another project that uses delayed_job and ran into the same problem. I was able to fix it by just changing the order of the gems in the `Gemfile`. Make sure you have delayed_job after newrelic_rpmin your gemfile

**Comment by benjaminoakes** [comment]
@crossman Good to know, thanks!

**Comment by bradrobertson** [comment]
I have a Sinatra app that I'm running DJ and Newrelic on... I still get this error:

> /Users/bradrobertson/.rvm/gems/ruby-1.9.3-p385@influitive-api/gems/newrelic_rpm-3.5.5.38/lib/new_relic/delayed_job_injection.rb: in block (2 levels) in <top (required)>
>     defined?(::Delayed) && defined?(::Delayed::Worker) && !NewRelic::Agent.config[:disable_dj]

**Comment by bradrobertson** [comment]
It should be noted that it's the require order that matters. I had a `require: false` in my Gemfile on newrelic and only required it in production.

This should be documented somewhere!

**Comment by alexlod** [comment]
I too have Sinatra + DJ + Newrelic. Not only does the `newrelic_rpm` gem need to be defined before `delayed_job_active_record` in `Gemfile`, it also needs to be required first. So in my Sinatra app I have something like this:

```
configure :production do
  require 'newrelic_rpm'
  require 'delayed_job'
  setup_delayed_job!
end

configure :test, :development do
  require 'delayed_job'
  setup_delayed_job!
end
```

**Pull request closed without merging**
